### ISSUE TITLE
ability to move window

### ISSUE THREAD

**Issue by JenSchutte** [srinathh/snippetfu#1]
When I click on things it’s giving me a message at the bottom of the screen but I can’t read it because my menu bar is on top of it.  I tried dragging the snippetfu window higher so it’s not overlapping with the menu bar and it won’t let me move it.  Can you make it so I can move the window by grabbing it from anywhere in the window and dragging it to a new place on the screen?  Thanks!

**Comment by srinathh** [comment]
Should be fixed by V2 update which uses platform native windows
